Housing spotlight
pph-collective/signal-app pull request #157
Opened 2022-08-03 15:40 UTC by s-bessey

Adds housing spotlight page (draft with no data)

2023-02-17 16:38 UTC, eldu requested changes
Okay I made a lot of comments... This is absolutely amazing work! Thanks so much Sam!

I got some weird bug? The help text isn't showing when I choose these options
![Screen Shot 2023-02-17 at 10 14 11 AM](https://user-images.githubusercontent.com/5270855/219708270-bd72fc07-c2e6-415d-88a4-3f760d7ad158.png)

2023-02-17 16:38 UTC, eldu commented on src/views/spotlights/housing/dashboard.vue
> +      <div class="content">
Let's add ini some padding so the content is indented in

```suggestion
      <div class="content px-4">
```

2023-02-17 16:38 UTC, eldu commented on src/views/spotlights/housing/dashboard.vue
>        <ControlPanel
In the ControlPanel file, can you add in the class "label" to the Label there? It gives some extra spacing.

```vue
      <label :for="type" class="label is-family-primary"
        ><strong>{{ options.label }}</strong></label
      >
```

2023-02-17 16:38 UTC, eldu commented on src/views/spotlights/housing/dashboard.vue
> +      </div>
Actually!! Can this text be put into the variable dropDowns as `description` or something? That way the control panel can handle the display of this text instead. Let me know if that makes any sense!

2023-02-21 16:33 UTC, s-bessey commented on src/components/dashboard/BarChart.vue
> +    // TODO: include numbers on chart
@maxwellkrieger Do you think we need actual numbers here? I feel like they'd be more confusing than helpful.

2023-02-21 16:34 UTC, s-bessey commented on src/components/dashboard/BarChart.vue
> +          title: "Rate Per 1,000", // TODO make "case" instead of "cases"
Nope!

2023-02-21 16:36 UTC, s-bessey commented on src/views/spotlights/housing/dashboard.vue
> +                  close proximity and/or sharing living facilities (e.g.,
Sending text as-is to RIDOH here, we'll see what they say

2023-02-23 15:23 UTC, eldu commented
Can we keep the colors consistent for both of these graphs? Feedback from our GSDC meeting~ ❤️ 💟 😍 

![Screenshot 2023-02-23 at 10 23 23 AM](https://user-images.githubusercontent.com/5270855/220950635-ae73e19e-49fa-4c56-92b3-d3efc38c16c4.png)
![Screenshot 2023-02-23 at 10 23 18 AM](https://user-images.githubusercontent.com/5270855/220950688-dc62a096-544a-40e1-99f7-46af6e4d75e3.png)

2023-03-08 14:27 UTC, eldu approved these changes
Thanks so much Sam! This looks great~

2023-03-08 14:32 UTC, merged