feat: Case hotspots
pph-collective/signal-app pull request #229
Opened 2024-04-11 15:23 UTC by maxwellkrieger

2024-04-11 15:30 UTC, eldu commented
I'm going to take a look at fixing up the gap chart !

2024-04-11 15:33 UTC, maxwellkrieger commented
@eldu to investigate squishification

2024-04-18 15:17 UTC, eldu requested changes
@s-bessey

2024-04-18 15:17 UTC, eldu commented on src/views/historical/testing-gap/dashboard.vue
Remove from this pr, it's in #223 

remove dashboard and index.vue

2024-04-23 15:25 UTC, eldu commented on src/views/historical/case-hotspot/index.vue
> +// const datasetName = "case_hotspots";
Ooohhhhhhh commented out code

2024-04-23 15:27 UTC, eldu commented on src/utils/utils.ts
> +  // if NaN, make MIN_VALUE
Wondering if it should be 0, but I'm also okay with Number.MIN_VALUE !

2024-04-23 20:17 UTC, s-bessey commented on src/views/historical/case-hotspot/index.vue
> +// const datasetName = "case_hotspots";
Oh noooo

2024-04-25 15:12 UTC, merged